---

spring:
  profiles: standalone

server:
  port: 8010


eureka:
  instance:
    hostname: localhost
  client:
    # 设置是否从注册中心获取注册信息,因为这是一个单点的EurekaServer,不需要同步其他EurekaServer节点数据,设为false
    fetch-registry: false
    # 设置是否将自己作为客户端注册到注册中心（缺省true)这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/


---
# java -jar -Dspring.profiles.active=peer1 target/xx.jar

spring:
  profiles: peer1                                 # 指定profile=peer1

eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8011/eureka/      # 将自己注册到peer2这个Eureka上面去

server:
  port: 8011

---

spring:
  profiles: peer2

eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer1:8012/eureka/

server:
  port: 8012
